<a href="https://colab.research.google.com/github/peonasayson/ds-exercises/blob/main/COM232_SAYSON_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PURPOSE:**
The purpose of prediction in this dataset is to use students' attendance records and other related details to estimate their likely grades. This helps us to identify the patterns between attendance and their performance, allowing early detection of students who may be at risk of failing. The datasets initially had many inconsistencies, errors, unnecessary characters, and missing values.


**DATA PROCESSING**

1. I removed unnecessary characters such as ., \/, and -. I used strip to remove slashes since they were at the beginning and end of a string, while for the dot and dash, I used replace since they were in the middle of a string.

2. I fixed misspelled words using replace, such as changing “fail” to “F” and “pass” to “P”.

3. I converted all attendance statuses to lowercase so I could correct their misspellings. For example, “absnt” became “absent”, “early left” became “absent”, and “late” also became “absent”.

4. After that, I capitalized the first letter of each word using str.title.

5. I arranged the subjects in alphabetical order to make them clearer and easier to read.

6. I dropped the rows in the student grade column that had “N/A”.

7. I used df.count() to check how many records were left.

8. Lastly, I reset the index so the numbering was correct.

In [ ]:
#import library
import pandas as pd
pd.set_option('display.max_rows', 110)
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datasets/attendance.csv')
df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0     S06592.  20/09/2024     Arabic           Present          Pass
1      S01777  22/01/2025       Math           Present             P
2      S07362  03/12/2024  Geography          PRESENT              p
3      S12119  16/03/2024  Geography           excused           NaN
4      S02002  24/05/2024       Math          PRESENT              P
5      S11872  13/03/2024  Geography           excused           NaN
6     S03196/  10/07/2024  Geography           excused           NaN
7      S08589  10/07/2024       Math              late           NaN
8      S09604  06/08/2024     Arabic            Absent          Fail
9      S00870  11/12/2024     Arabic        left early            F
10    \S04335  25/03/2024  Geography              Late           NaN
11     S03614  16/11/2024  Geography              Late           NaN
12    S.04868  14/10/2024       Math        left early          Fail
13     S11462  07/01/2025     Arabic        left early             F
14     S02096  01/01/2025       Math           Present          Pass
15     S01258  08/05/2024  Geography        left early          Fail
16     S10696  25/06/2024     Arabic              late           NaN
17     S07045  16/01/2025       Math              Late           NaN
18     S05335  21/11/2024    Science           Present          Pass
19     S07904  12/01/2025     Arabic             absnt          Fail
20     S10897  24/06/2024     Arabic              Late           NaN
21     S04730  28/01/2025    History        left early          Fail
22     S11886  11/11/2024  Geography           Present          Pass
23     S05903  07/12/2024    English              late           NaN
24     S07581  13/06/2024       Math              late           NaN
25     S04790  28/10/2024       Math           excused           NaN
26     S00923  07/10/2024    Science            Absent          Fail
27     S06107  14/11/2024    Science          PRESENT              P
28     S04002  29/06/2024    English             absnt          Fail
29     S06390  02/08/2024       Math           Present             P
30     S03733  24/06/2024    History          PRESENT           Pass
31     S03131  09/01/2025    Science           excused           NaN
32     S00098  22/10/2024    History              late           NaN
33     S07123  17/09/2024    History              Late           NaN
34     S07174  24/05/2024  Geography           Present          Pass
35     S10359  02/10/2024    English           Present             P
36     S07484  12/10/2024       Math              Late           NaN
37     S02154  16/08/2024     Arabic           excused           NaN
38     S06923  09/03/2024    English        left early             F
39     S02643  30/08/2024     Arabic        left early          Fail
40     S05477  26/09/2024     Arabic             absnt             F
41     S04173  07/07/2024  Geography           excused           NaN
42     S11830  11/02/2025       Math             absnt          fail
43     S05599  26/05/2024  Geography          PRESENT              P
44     S06854  16/06/2024     Arabic              late           NaN
45    S07-816  25/04/2024    History             absnt             F
46     S03711  19/01/2025    History        left early          Fail
47     S09400  12/12/2024    Science        left early          Fail
48     S01923  18/12/2024    History           excused           NaN
49     S03399  17/10/2024    English        left early          Fail
50     S02512  06/09/2024    English           excused           NaN
51     S04968  09/05/2024     Arabic          PRESENT              P
52     S05411  05/12/2024  Geography             absnt             F
53     S00092  15/01/2025    Science              late           NaN
54     S04268  14/06/2024    Science              late           NaN
55     S00728  01/07/2024    English            Absent          Fail
56     S00791  17/02/2025       Math              Late           NaN
57     S03980  09/08/2024    History              late           NaN
58     S07782  19/03/2024    History          PRESENT           Pass
59     S11206  14/07/2024    English            Absent          Fail
60     S05315  05/06/2024    English              Late           NaN
61     S10058  18/01/2025       Math            Absent          Fail
62     S09580  29/05/2024  Geography            Absent          Fail
63     S03919  31/10/2024    Science        left early          Fail
64     S09907  24/02/2025  Geography        left early          Fail
65     S11748  04/06/2024    Science              late           NaN
66     S08504  03/01/2025     Arabic             absnt             F
67     S09880  05/05/2024       Math           Present          Pass
68     S04411  05/06/2024    History            Absent          Fail
69    S0-5864  09/10/2024    English              late           NaN
70     S11872  25/11/2024     Arabic           excused           NaN
71     S08212  21/08/2024    English        left early          Fail
72     S09939  20/11/2024    English              Late           NaN
73     S11868  03/09/2024    English             absnt           NaN
74     S00393  05/02/2025  Geography             absnt             F
75     S03713  07/09/2024    English             absnt           NaN
76     S02538  02/08/2024    History        left early          Fail
77     S11397  19/01/2025    History        left early          Fail
78     S06823  04/10/2024    English           Present          Pass
79     S02860  23/07/2024       Math             absnt           NaN
80     S03714  01/07/2024    Science            Absent          Fail
81     S09252  30/11/2024    English           excused           NaN
82     S01796  19/02/2025    History          PRESENT            NaN
83     S01735  29/03/2024  Geography              late           NaN
84     S04703  28/03/2024     Arabic            Absent          Fail
85     S10917  14/08/2024  Geography          PRESENT            NaN
86     S10547  29/07/2024    History              Late           NaN
87     S05199  02/05/2024    Science              late           NaN
88     S04190  20/09/2024  Geography           excused           NaN
89     S04423  25/07/2024    History           Present          Pass
90     S09721  17/04/2024    English              Late           NaN
91     S08376  23/11/2024    History              Late           NaN
92     S06700  18/03/2024  Geography           excused           NaN
93     S01952  02/07/2024     Arabic        left early          Fail
94     S11075  17/06/2024       Math            Absent          Fail
95     S10876  22/10/2024  Geography              late           NaN
96     S01616  03/09/2024    Science           excused           NaN
97    S083-73  13/05/2024       Math            Absent          Fail
98     S10677  11/08/2024       Math              late           NaN

In [ ]:
df["Student_ID"] = df["Student_ID"].str.replace(".", "")
df["Student_ID"] = df["Student_ID"].str.replace("-", "")
df["Student_ID"] = df["Student_ID"].str.strip("\/")


df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0      S06592  20/09/2024     Arabic           Present          Pass
1      S01777  22/01/2025       Math           Present             P
2      S07362  03/12/2024  Geography          PRESENT              p
3      S12119  16/03/2024  Geography           excused           NaN
4      S02002  24/05/2024       Math          PRESENT              P
5      S11872  13/03/2024  Geography           excused           NaN
6      S03196  10/07/2024  Geography           excused           NaN
7      S08589  10/07/2024       Math              late           NaN
8      S09604  06/08/2024     Arabic            Absent          Fail
9      S00870  11/12/2024     Arabic        left early            F
10     S04335  25/03/2024  Geography              Late           NaN
11     S03614  16/11/2024  Geography              Late           NaN
12     S04868  14/10/2024       Math        left early          Fail
13     S11462  07/01/2025     Arabic        left early             F
14     S02096  01/01/2025       Math           Present          Pass
15     S01258  08/05/2024  Geography        left early          Fail
16     S10696  25/06/2024     Arabic              late           NaN
17     S07045  16/01/2025       Math              Late           NaN
18     S05335  21/11/2024    Science           Present          Pass
19     S07904  12/01/2025     Arabic             absnt          Fail
20     S10897  24/06/2024     Arabic              Late           NaN
21     S04730  28/01/2025    History        left early          Fail
22     S11886  11/11/2024  Geography           Present          Pass
23     S05903  07/12/2024    English              late           NaN
24     S07581  13/06/2024       Math              late           NaN
25     S04790  28/10/2024       Math           excused           NaN
26     S00923  07/10/2024    Science            Absent          Fail
27     S06107  14/11/2024    Science          PRESENT              P
28     S04002  29/06/2024    English             absnt          Fail
29     S06390  02/08/2024       Math           Present             P
30     S03733  24/06/2024    History          PRESENT           Pass
31     S03131  09/01/2025    Science           excused           NaN
32     S00098  22/10/2024    History              late           NaN
33     S07123  17/09/2024    History              Late           NaN
34     S07174  24/05/2024  Geography           Present          Pass
35     S10359  02/10/2024    English           Present             P
36     S07484  12/10/2024       Math              Late           NaN
37     S02154  16/08/2024     Arabic           excused           NaN
38     S06923  09/03/2024    English        left early             F
39     S02643  30/08/2024     Arabic        left early          Fail
40     S05477  26/09/2024     Arabic             absnt             F
41     S04173  07/07/2024  Geography           excused           NaN
42     S11830  11/02/2025       Math             absnt          fail
43     S05599  26/05/2024  Geography          PRESENT              P
44     S06854  16/06/2024     Arabic              late           NaN
45     S07816  25/04/2024    History             absnt             F
46     S03711  19/01/2025    History        left early          Fail
47     S09400  12/12/2024    Science        left early          Fail
48     S01923  18/12/2024    History           excused           NaN
49     S03399  17/10/2024    English        left early          Fail
50     S02512  06/09/2024    English           excused           NaN
51     S04968  09/05/2024     Arabic          PRESENT              P
52     S05411  05/12/2024  Geography             absnt             F
53     S00092  15/01/2025    Science              late           NaN
54     S04268  14/06/2024    Science              late           NaN
55     S00728  01/07/2024    English            Absent          Fail
56     S00791  17/02/2025       Math              Late           NaN
57     S03980  09/08/2024    History              late           NaN
58     S07782  19/03/2024    History          PRESENT           Pass
59     S11206  14/07/2024    English            Absent          Fail
60     S05315  05/06/2024    English              Late           NaN
61     S10058  18/01/2025       Math            Absent          Fail
62     S09580  29/05/2024  Geography            Absent          Fail
63     S03919  31/10/2024    Science        left early          Fail
64     S09907  24/02/2025  Geography        left early          Fail
65     S11748  04/06/2024    Science              late           NaN
66     S08504  03/01/2025     Arabic             absnt             F
67     S09880  05/05/2024       Math           Present          Pass
68     S04411  05/06/2024    History            Absent          Fail
69     S05864  09/10/2024    English              late           NaN
70     S11872  25/11/2024     Arabic           excused           NaN
71     S08212  21/08/2024    English        left early          Fail
72     S09939  20/11/2024    English              Late           NaN
73     S11868  03/09/2024    English             absnt           NaN
74     S00393  05/02/2025  Geography             absnt             F
75     S03713  07/09/2024    English             absnt           NaN
76     S02538  02/08/2024    History        left early          Fail
77     S11397  19/01/2025    History        left early          Fail
78     S06823  04/10/2024    English           Present          Pass
79     S02860  23/07/2024       Math             absnt           NaN
80     S03714  01/07/2024    Science            Absent          Fail
81     S09252  30/11/2024    English           excused           NaN
82     S01796  19/02/2025    History          PRESENT            NaN
83     S01735  29/03/2024  Geography              late           NaN
84     S04703  28/03/2024     Arabic            Absent          Fail
85     S10917  14/08/2024  Geography          PRESENT            NaN
86     S10547  29/07/2024    History              Late           NaN
87     S05199  02/05/2024    Science              late           NaN
88     S04190  20/09/2024  Geography           excused           NaN
89     S04423  25/07/2024    History           Present          Pass
90     S09721  17/04/2024    English              Late           NaN
91     S08376  23/11/2024    History              Late           NaN
92     S06700  18/03/2024  Geography           excused           NaN
93     S01952  02/07/2024     Arabic        left early          Fail
94     S11075  17/06/2024       Math            Absent          Fail
95     S10876  22/10/2024  Geography              late           NaN
96     S01616  03/09/2024    Science           excused           NaN
97     S08373  13/05/2024       Math            Absent          Fail
98     S10677  11/08/2024       Math              late           NaN

In [ ]:
df["Student_Grade"] = df["Student_Grade"].str.replace("Pass", "P").replace("Fail", "F").replace("fail", "F")
df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0      S06592  20/09/2024     Arabic           Present             P
1      S01777  22/01/2025       Math           Present             P
2      S07362  03/12/2024  Geography          PRESENT              p
3      S12119  16/03/2024  Geography           excused           NaN
4      S02002  24/05/2024       Math          PRESENT              P
5      S11872  13/03/2024  Geography           excused           NaN
6      S03196  10/07/2024  Geography           excused           NaN
7      S08589  10/07/2024       Math              late           NaN
8      S09604  06/08/2024     Arabic            Absent             F
9      S00870  11/12/2024     Arabic        left early            F
10     S04335  25/03/2024  Geography              Late           NaN
11     S03614  16/11/2024  Geography              Late           NaN
12     S04868  14/10/2024       Math        left early             F
13     S11462  07/01/2025     Arabic        left early             F
14     S02096  01/01/2025       Math           Present             P
15     S01258  08/05/2024  Geography        left early             F
16     S10696  25/06/2024     Arabic              late           NaN
17     S07045  16/01/2025       Math              Late           NaN
18     S05335  21/11/2024    Science           Present             P
19     S07904  12/01/2025     Arabic             absnt             F
20     S10897  24/06/2024     Arabic              Late           NaN
21     S04730  28/01/2025    History        left early             F
22     S11886  11/11/2024  Geography           Present             P
23     S05903  07/12/2024    English              late           NaN
24     S07581  13/06/2024       Math              late           NaN
25     S04790  28/10/2024       Math           excused           NaN
26     S00923  07/10/2024    Science            Absent             F
27     S06107  14/11/2024    Science          PRESENT              P
28     S04002  29/06/2024    English             absnt             F
29     S06390  02/08/2024       Math           Present             P
30     S03733  24/06/2024    History          PRESENT              P
31     S03131  09/01/2025    Science           excused           NaN
32     S00098  22/10/2024    History              late           NaN
33     S07123  17/09/2024    History              Late           NaN
34     S07174  24/05/2024  Geography           Present             P
35     S10359  02/10/2024    English           Present             P
36     S07484  12/10/2024       Math              Late           NaN
37     S02154  16/08/2024     Arabic           excused           NaN
38     S06923  09/03/2024    English        left early             F
39     S02643  30/08/2024     Arabic        left early             F
40     S05477  26/09/2024     Arabic             absnt             F
41     S04173  07/07/2024  Geography           excused           NaN
42     S11830  11/02/2025       Math             absnt             F
43     S05599  26/05/2024  Geography          PRESENT              P
44     S06854  16/06/2024     Arabic              late           NaN
45     S07816  25/04/2024    History             absnt             F
46     S03711  19/01/2025    History        left early             F
47     S09400  12/12/2024    Science        left early             F
48     S01923  18/12/2024    History           excused           NaN
49     S03399  17/10/2024    English        left early             F
50     S02512  06/09/2024    English           excused           NaN
51     S04968  09/05/2024     Arabic          PRESENT              P
52     S05411  05/12/2024  Geography             absnt             F
53     S00092  15/01/2025    Science              late           NaN
54     S04268  14/06/2024    Science              late           NaN
55     S00728  01/07/2024    English            Absent             F
56     S00791  17/02/2025       Math              Late           NaN
57     S03980  09/08/2024    History              late           NaN
58     S07782  19/03/2024    History          PRESENT              P
59     S11206  14/07/2024    English            Absent             F
60     S05315  05/06/2024    English              Late           NaN
61     S10058  18/01/2025       Math            Absent             F
62     S09580  29/05/2024  Geography            Absent             F
63     S03919  31/10/2024    Science        left early             F
64     S09907  24/02/2025  Geography        left early             F
65     S11748  04/06/2024    Science              late           NaN
66     S08504  03/01/2025     Arabic             absnt             F
67     S09880  05/05/2024       Math           Present             P
68     S04411  05/06/2024    History            Absent             F
69     S05864  09/10/2024    English              late           NaN
70     S11872  25/11/2024     Arabic           excused           NaN
71     S08212  21/08/2024    English        left early             F
72     S09939  20/11/2024    English              Late           NaN
73     S11868  03/09/2024    English             absnt           NaN
74     S00393  05/02/2025  Geography             absnt             F
75     S03713  07/09/2024    English             absnt           NaN
76     S02538  02/08/2024    History        left early             F
77     S11397  19/01/2025    History        left early             F
78     S06823  04/10/2024    English           Present             P
79     S02860  23/07/2024       Math             absnt           NaN
80     S03714  01/07/2024    Science            Absent             F
81     S09252  30/11/2024    English           excused           NaN
82     S01796  19/02/2025    History          PRESENT            NaN
83     S01735  29/03/2024  Geography              late           NaN
84     S04703  28/03/2024     Arabic            Absent             F
85     S10917  14/08/2024  Geography          PRESENT            NaN
86     S10547  29/07/2024    History              Late           NaN
87     S05199  02/05/2024    Science              late           NaN
88     S04190  20/09/2024  Geography           excused           NaN
89     S04423  25/07/2024    History           Present             P
90     S09721  17/04/2024    English              Late           NaN
91     S08376  23/11/2024    History              Late           NaN
92     S06700  18/03/2024  Geography           excused           NaN
93     S01952  02/07/2024     Arabic        left early             F
94     S11075  17/06/2024       Math            Absent             F
95     S10876  22/10/2024  Geography              late           NaN
96     S01616  03/09/2024    Science           excused           NaN
97     S08373  13/05/2024       Math            Absent             F
98     S10677  11/08/2024       Math              late           NaN

In [ ]:
df["Attendance_Status"] = df["Attendance_Status"].str.lower()

df["Attendance_Status"] = df["Attendance_Status"].str.replace("left early", "absent").replace("late", "absent").replace("absnt", "absent")
df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0      S06592  20/09/2024     Arabic           present             P
1      S01777  22/01/2025       Math           present             P
2      S07362  03/12/2024  Geography          present              p
3      S12119  16/03/2024  Geography           excused           NaN
4      S02002  24/05/2024       Math          present              P
5      S11872  13/03/2024  Geography           excused           NaN
6      S03196  10/07/2024  Geography           excused           NaN
7      S08589  10/07/2024       Math              late           NaN
8      S09604  06/08/2024     Arabic            absent             F
9      S00870  11/12/2024     Arabic            absent            F
10     S04335  25/03/2024  Geography            absent           NaN
11     S03614  16/11/2024  Geography            absent           NaN
12     S04868  14/10/2024       Math            absent             F
13     S11462  07/01/2025     Arabic            absent             F
14     S02096  01/01/2025       Math           present             P
15     S01258  08/05/2024  Geography            absent             F
16     S10696  25/06/2024     Arabic              late           NaN
17     S07045  16/01/2025       Math            absent           NaN
18     S05335  21/11/2024    Science           present             P
19     S07904  12/01/2025     Arabic            absent             F
20     S10897  24/06/2024     Arabic            absent           NaN
21     S04730  28/01/2025    History            absent             F
22     S11886  11/11/2024  Geography           present             P
23     S05903  07/12/2024    English              late           NaN
24     S07581  13/06/2024       Math              late           NaN
25     S04790  28/10/2024       Math           excused           NaN
26     S00923  07/10/2024    Science            absent             F
27     S06107  14/11/2024    Science          present              P
28     S04002  29/06/2024    English            absent             F
29     S06390  02/08/2024       Math           present             P
30     S03733  24/06/2024    History          present              P
31     S03131  09/01/2025    Science           excused           NaN
32     S00098  22/10/2024    History              late           NaN
33     S07123  17/09/2024    History            absent           NaN
34     S07174  24/05/2024  Geography           present             P
35     S10359  02/10/2024    English           present             P
36     S07484  12/10/2024       Math            absent           NaN
37     S02154  16/08/2024     Arabic           excused           NaN
38     S06923  09/03/2024    English            absent             F
39     S02643  30/08/2024     Arabic            absent             F
40     S05477  26/09/2024     Arabic            absent             F
41     S04173  07/07/2024  Geography           excused           NaN
42     S11830  11/02/2025       Math            absent             F
43     S05599  26/05/2024  Geography          present              P
44     S06854  16/06/2024     Arabic              late           NaN
45     S07816  25/04/2024    History            absent             F
46     S03711  19/01/2025    History            absent             F
47     S09400  12/12/2024    Science            absent             F
48     S01923  18/12/2024    History           excused           NaN
49     S03399  17/10/2024    English            absent             F
50     S02512  06/09/2024    English           excused           NaN
51     S04968  09/05/2024     Arabic          present              P
52     S05411  05/12/2024  Geography            absent             F
53     S00092  15/01/2025    Science              late           NaN
54     S04268  14/06/2024    Science              late           NaN
55     S00728  01/07/2024    English            absent             F
56     S00791  17/02/2025       Math            absent           NaN
57     S03980  09/08/2024    History              late           NaN
58     S07782  19/03/2024    History          present              P
59     S11206  14/07/2024    English            absent             F
60     S05315  05/06/2024    English            absent           NaN
61     S10058  18/01/2025       Math            absent             F
62     S09580  29/05/2024  Geography            absent             F
63     S03919  31/10/2024    Science            absent             F
64     S09907  24/02/2025  Geography            absent             F
65     S11748  04/06/2024    Science              late           NaN
66     S08504  03/01/2025     Arabic            absent             F
67     S09880  05/05/2024       Math           present             P
68     S04411  05/06/2024    History            absent             F
69     S05864  09/10/2024    English              late           NaN
70     S11872  25/11/2024     Arabic           excused           NaN
71     S08212  21/08/2024    English            absent             F
72     S09939  20/11/2024    English            absent           NaN
73     S11868  03/09/2024    English            absent           NaN
74     S00393  05/02/2025  Geography            absent             F
75     S03713  07/09/2024    English            absent           NaN
76     S02538  02/08/2024    History            absent             F
77     S11397  19/01/2025    History            absent             F
78     S06823  04/10/2024    English           present             P
79     S02860  23/07/2024       Math            absent           NaN
80     S03714  01/07/2024    Science            absent             F
81     S09252  30/11/2024    English           excused           NaN
82     S01796  19/02/2025    History          present            NaN
83     S01735  29/03/2024  Geography              late           NaN
84     S04703  28/03/2024     Arabic            absent             F
85     S10917  14/08/2024  Geography          present            NaN
86     S10547  29/07/2024    History            absent           NaN
87     S05199  02/05/2024    Science              late           NaN
88     S04190  20/09/2024  Geography           excused           NaN
89     S04423  25/07/2024    History           present             P
90     S09721  17/04/2024    English            absent           NaN
91     S08376  23/11/2024    History            absent           NaN
92     S06700  18/03/2024  Geography           excused           NaN
93     S01952  02/07/2024     Arabic            absent             F
94     S11075  17/06/2024       Math            absent             F
95     S10876  22/10/2024  Geography              late           NaN
96     S01616  03/09/2024    Science           excused           NaN
97     S08373  13/05/2024       Math            absent             F
98     S10677  11/08/2024       Math              late           NaN

In [ ]:
df["Attendance_Status"] = df["Attendance_Status"].str.title()
df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0      S06592  20/09/2024     Arabic           Present             P
1      S01777  22/01/2025       Math           Present             P
2      S07362  03/12/2024  Geography          Present              p
3      S12119  16/03/2024  Geography           Excused           NaN
4      S02002  24/05/2024       Math          Present              P
5      S11872  13/03/2024  Geography           Excused           NaN
6      S03196  10/07/2024  Geography           Excused           NaN
7      S08589  10/07/2024       Math              Late           NaN
8      S09604  06/08/2024     Arabic            Absent             F
9      S00870  11/12/2024     Arabic            Absent            F
10     S04335  25/03/2024  Geography            Absent           NaN
11     S03614  16/11/2024  Geography            Absent           NaN
12     S04868  14/10/2024       Math            Absent             F
13     S11462  07/01/2025     Arabic            Absent             F
14     S02096  01/01/2025       Math           Present             P
15     S01258  08/05/2024  Geography            Absent             F
16     S10696  25/06/2024     Arabic              Late           NaN
17     S07045  16/01/2025       Math            Absent           NaN
18     S05335  21/11/2024    Science           Present             P
19     S07904  12/01/2025     Arabic            Absent             F
20     S10897  24/06/2024     Arabic            Absent           NaN
21     S04730  28/01/2025    History            Absent             F
22     S11886  11/11/2024  Geography           Present             P
23     S05903  07/12/2024    English              Late           NaN
24     S07581  13/06/2024       Math              Late           NaN
25     S04790  28/10/2024       Math           Excused           NaN
26     S00923  07/10/2024    Science            Absent             F
27     S06107  14/11/2024    Science          Present              P
28     S04002  29/06/2024    English            Absent             F
29     S06390  02/08/2024       Math           Present             P
30     S03733  24/06/2024    History          Present              P
31     S03131  09/01/2025    Science           Excused           NaN
32     S00098  22/10/2024    History              Late           NaN
33     S07123  17/09/2024    History            Absent           NaN
34     S07174  24/05/2024  Geography           Present             P
35     S10359  02/10/2024    English           Present             P
36     S07484  12/10/2024       Math            Absent           NaN
37     S02154  16/08/2024     Arabic           Excused           NaN
38     S06923  09/03/2024    English            Absent             F
39     S02643  30/08/2024     Arabic            Absent             F
40     S05477  26/09/2024     Arabic            Absent             F
41     S04173  07/07/2024  Geography           Excused           NaN
42     S11830  11/02/2025       Math            Absent             F
43     S05599  26/05/2024  Geography          Present              P
44     S06854  16/06/2024     Arabic              Late           NaN
45     S07816  25/04/2024    History            Absent             F
46     S03711  19/01/2025    History            Absent             F
47     S09400  12/12/2024    Science            Absent             F
48     S01923  18/12/2024    History           Excused           NaN
49     S03399  17/10/2024    English            Absent             F
50     S02512  06/09/2024    English           Excused           NaN
51     S04968  09/05/2024     Arabic          Present              P
52     S05411  05/12/2024  Geography            Absent             F
53     S00092  15/01/2025    Science              Late           NaN
54     S04268  14/06/2024    Science              Late           NaN
55     S00728  01/07/2024    English            Absent             F
56     S00791  17/02/2025       Math            Absent           NaN
57     S03980  09/08/2024    History              Late           NaN
58     S07782  19/03/2024    History          Present              P
59     S11206  14/07/2024    English            Absent             F
60     S05315  05/06/2024    English            Absent           NaN
61     S10058  18/01/2025       Math            Absent             F
62     S09580  29/05/2024  Geography            Absent             F
63     S03919  31/10/2024    Science            Absent             F
64     S09907  24/02/2025  Geography            Absent             F
65     S11748  04/06/2024    Science              Late           NaN
66     S08504  03/01/2025     Arabic            Absent             F
67     S09880  05/05/2024       Math           Present             P
68     S04411  05/06/2024    History            Absent             F
69     S05864  09/10/2024    English              Late           NaN
70     S11872  25/11/2024     Arabic           Excused           NaN
71     S08212  21/08/2024    English            Absent             F
72     S09939  20/11/2024    English            Absent           NaN
73     S11868  03/09/2024    English            Absent           NaN
74     S00393  05/02/2025  Geography            Absent             F
75     S03713  07/09/2024    English            Absent           NaN
76     S02538  02/08/2024    History            Absent             F
77     S11397  19/01/2025    History            Absent             F
78     S06823  04/10/2024    English           Present             P
79     S02860  23/07/2024       Math            Absent           NaN
80     S03714  01/07/2024    Science            Absent             F
81     S09252  30/11/2024    English           Excused           NaN
82     S01796  19/02/2025    History          Present            NaN
83     S01735  29/03/2024  Geography              Late           NaN
84     S04703  28/03/2024     Arabic            Absent             F
85     S10917  14/08/2024  Geography          Present            NaN
86     S10547  29/07/2024    History            Absent           NaN
87     S05199  02/05/2024    Science              Late           NaN
88     S04190  20/09/2024  Geography           Excused           NaN
89     S04423  25/07/2024    History           Present             P
90     S09721  17/04/2024    English            Absent           NaN
91     S08376  23/11/2024    History            Absent           NaN
92     S06700  18/03/2024  Geography           Excused           NaN
93     S01952  02/07/2024     Arabic            Absent             F
94     S11075  17/06/2024       Math            Absent             F
95     S10876  22/10/2024  Geography              Late           NaN
96     S01616  03/09/2024    Science           Excused           NaN
97     S08373  13/05/2024       Math            Absent             F
98     S10677  11/08/2024       Math              Late           NaN

In [ ]:
df = df.sort_values(by='Subject', ascending=True).reset_index(drop=True)
df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0      S06592  20/09/2024     Arabic           Present             P
1      S10696  25/06/2024     Arabic              Late           NaN
2      S08504  03/01/2025     Arabic            Absent             F
3      S02154  16/08/2024     Arabic           Excused           NaN
4      S11462  07/01/2025     Arabic            Absent             F
5      S11872  25/11/2024     Arabic           Excused           NaN
6      S04968  09/05/2024     Arabic          Present              P
7      S10897  24/06/2024     Arabic            Absent           NaN
8      S00870  11/12/2024     Arabic            Absent            F
9      S06854  16/06/2024     Arabic              Late           NaN
10     S05477  26/09/2024     Arabic            Absent             F
11     S02643  30/08/2024     Arabic            Absent             F
12     S04703  28/03/2024     Arabic            Absent             F
13     S01952  02/07/2024     Arabic            Absent             F
14     S09604  06/08/2024     Arabic            Absent             F
15     S07904  12/01/2025     Arabic            Absent             F
16     S02512  06/09/2024    English           Excused           NaN
17     S00728  01/07/2024    English            Absent             F
18     S06923  09/03/2024    English            Absent             F
19     S05864  09/10/2024    English              Late           NaN
20     S05315  05/06/2024    English            Absent           NaN
21     S08212  21/08/2024    English            Absent             F
22     S09939  20/11/2024    English            Absent           NaN
23     S11868  03/09/2024    English            Absent           NaN
24     S03713  07/09/2024    English            Absent           NaN
25     S06823  04/10/2024    English           Present             P
26     S09252  30/11/2024    English           Excused           NaN
27     S09721  17/04/2024    English            Absent           NaN
28     S11206  14/07/2024    English            Absent             F
29     S10359  02/10/2024    English           Present             P
30     S03399  17/10/2024    English            Absent             F
31     S04002  29/06/2024    English            Absent             F
32     S05903  07/12/2024    English              Late           NaN
33     S09907  24/02/2025  Geography            Absent             F
34     S00393  05/02/2025  Geography            Absent             F
35     S03196  10/07/2024  Geography           Excused           NaN
36     S01258  08/05/2024  Geography            Absent             F
37     S11872  13/03/2024  Geography           Excused           NaN
38     S09580  29/05/2024  Geography            Absent             F
39     S01735  29/03/2024  Geography              Late           NaN
40     S12119  16/03/2024  Geography           Excused           NaN
41     S10917  14/08/2024  Geography          Present            NaN
42     S05411  05/12/2024  Geography            Absent             F
43     S03614  16/11/2024  Geography            Absent           NaN
44     S04190  20/09/2024  Geography           Excused           NaN
45     S11886  11/11/2024  Geography           Present             P
46     S04335  25/03/2024  Geography            Absent           NaN
47     S05599  26/05/2024  Geography          Present              P
48     S07362  03/12/2024  Geography          Present              p
49     S04173  07/07/2024  Geography           Excused           NaN
50     S06700  18/03/2024  Geography           Excused           NaN
51     S07174  24/05/2024  Geography           Present             P
52     S10876  22/10/2024  Geography              Late           NaN
53     S00098  22/10/2024    History              Late           NaN
54     S07123  17/09/2024    History            Absent           NaN
55     S04411  05/06/2024    History            Absent             F
56     S02538  02/08/2024    History            Absent             F
57     S11397  19/01/2025    History            Absent             F
58     S03733  24/06/2024    History          Present              P
59     S03711  19/01/2025    History            Absent             F
60     S07782  19/03/2024    History          Present              P
61     S03980  09/08/2024    History              Late           NaN
62     S04730  28/01/2025    History            Absent             F
63     S08376  23/11/2024    History            Absent           NaN
64     S10547  29/07/2024    History            Absent           NaN
65     S01923  18/12/2024    History           Excused           NaN
66     S04423  25/07/2024    History           Present             P
67     S07816  25/04/2024    History            Absent             F
68     S01796  19/02/2025    History          Present            NaN
69     S02002  24/05/2024       Math          Present              P
70     S02860  23/07/2024       Math            Absent           NaN
71     S11075  17/06/2024       Math            Absent             F
72     S01777  22/01/2025       Math           Present             P
73     S10677  11/08/2024       Math              Late           NaN
74     S04868  14/10/2024       Math            Absent             F
75     S06390  02/08/2024       Math           Present             P
76     S07484  12/10/2024       Math            Absent           NaN
77     S04790  28/10/2024       Math           Excused           NaN
78     S11830  11/02/2025       Math            Absent             F
79     S07581  13/06/2024       Math              Late           NaN
80     S08589  10/07/2024       Math              Late           NaN
81     S00791  17/02/2025       Math            Absent           NaN
82     S08373  13/05/2024       Math            Absent             F
83     S07045  16/01/2025       Math            Absent           NaN
84     S10058  18/01/2025       Math            Absent             F
85     S09880  05/05/2024       Math           Present             P
86     S02096  01/01/2025       Math           Present             P
87     S04268  14/06/2024    Science              Late           NaN
88     S00092  15/01/2025    Science              Late           NaN
89     S03714  01/07/2024    Science            Absent             F
90     S05199  02/05/2024    Science              Late           NaN
91     S09400  12/12/2024    Science            Absent             F
92     S03919  31/10/2024    Science            Absent             F
93     S11748  04/06/2024    Science              Late           NaN
94     S00923  07/10/2024    Science            Absent             F
95     S06107  14/11/2024    Science          Present              P
96     S01616  03/09/2024    Science           Excused           NaN
97     S05335  21/11/2024    Science           Present             P
98     S03131  09/01/2025    Science           Excused           NaN

In [ ]:
# drop empty cell
for x in df.index:
    if pd.isna(df.loc[x, "Student_Grade"]):
        df.drop(x, inplace=True)
df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0      S06592  20/09/2024     Arabic           Present             P
2      S08504  03/01/2025     Arabic            Absent             F
4      S11462  07/01/2025     Arabic            Absent             F
6      S04968  09/05/2024     Arabic          Present              P
8      S00870  11/12/2024     Arabic            Absent            F
10     S05477  26/09/2024     Arabic            Absent             F
11     S02643  30/08/2024     Arabic            Absent             F
12     S04703  28/03/2024     Arabic            Absent             F
13     S01952  02/07/2024     Arabic            Absent             F
14     S09604  06/08/2024     Arabic            Absent             F
15     S07904  12/01/2025     Arabic            Absent             F
17     S00728  01/07/2024    English            Absent             F
18     S06923  09/03/2024    English            Absent             F
21     S08212  21/08/2024    English            Absent             F
25     S06823  04/10/2024    English           Present             P
28     S11206  14/07/2024    English            Absent             F
29     S10359  02/10/2024    English           Present             P
30     S03399  17/10/2024    English            Absent             F
31     S04002  29/06/2024    English            Absent             F
33     S09907  24/02/2025  Geography            Absent             F
34     S00393  05/02/2025  Geography            Absent             F
36     S01258  08/05/2024  Geography            Absent             F
38     S09580  29/05/2024  Geography            Absent             F
42     S05411  05/12/2024  Geography            Absent             F
45     S11886  11/11/2024  Geography           Present             P
47     S05599  26/05/2024  Geography          Present              P
48     S07362  03/12/2024  Geography          Present              p
51     S07174  24/05/2024  Geography           Present             P
55     S04411  05/06/2024    History            Absent             F
56     S02538  02/08/2024    History            Absent             F
57     S11397  19/01/2025    History            Absent             F
58     S03733  24/06/2024    History          Present              P
59     S03711  19/01/2025    History            Absent             F
60     S07782  19/03/2024    History          Present              P
62     S04730  28/01/2025    History            Absent             F
66     S04423  25/07/2024    History           Present             P
67     S07816  25/04/2024    History            Absent             F
69     S02002  24/05/2024       Math          Present              P
71     S11075  17/06/2024       Math            Absent             F
72     S01777  22/01/2025       Math           Present             P
74     S04868  14/10/2024       Math            Absent             F
75     S06390  02/08/2024       Math           Present             P
78     S11830  11/02/2025       Math            Absent             F
82     S08373  13/05/2024       Math            Absent             F
84     S10058  18/01/2025       Math            Absent             F
85     S09880  05/05/2024       Math           Present             P
86     S02096  01/01/2025       Math           Present             P
89     S03714  01/07/2024    Science            Absent             F
91     S09400  12/12/2024    Science            Absent             F
92     S03919  31/10/2024    Science            Absent             F
94     S00923  07/10/2024    Science            Absent             F
95     S06107  14/11/2024    Science          Present              P
97     S05335  21/11/2024    Science           Present             P

In [ ]:
df.count()

Student_ID           53
Date                 53
Subject              53
Attendance_Status    53
Student_Grade        53
dtype: int64

In [ ]:
df = df.reset_index(drop=True)
df

   Student_ID        Date    Subject Attendance_Status Student_Grade
0      S06592  20/09/2024     Arabic           Present             P
1      S08504  03/01/2025     Arabic            Absent             F
2      S11462  07/01/2025     Arabic            Absent             F
3      S04968  09/05/2024     Arabic          Present              P
4      S00870  11/12/2024     Arabic            Absent            F
5      S05477  26/09/2024     Arabic            Absent             F
6      S02643  30/08/2024     Arabic            Absent             F
7      S04703  28/03/2024     Arabic            Absent             F
8      S01952  02/07/2024     Arabic            Absent             F
9      S09604  06/08/2024     Arabic            Absent             F
10     S07904  12/01/2025     Arabic            Absent             F
11     S00728  01/07/2024    English            Absent             F
12     S06923  09/03/2024    English            Absent             F
13     S08212  21/08/2024    English            Absent             F
14     S06823  04/10/2024    English           Present             P
15     S11206  14/07/2024    English            Absent             F
16     S10359  02/10/2024    English           Present             P
17     S03399  17/10/2024    English            Absent             F
18     S04002  29/06/2024    English            Absent             F
19     S09907  24/02/2025  Geography            Absent             F
20     S00393  05/02/2025  Geography            Absent             F
21     S01258  08/05/2024  Geography            Absent             F
22     S09580  29/05/2024  Geography            Absent             F
23     S05411  05/12/2024  Geography            Absent             F
24     S11886  11/11/2024  Geography           Present             P
25     S05599  26/05/2024  Geography          Present              P
26     S07362  03/12/2024  Geography          Present              p
27     S07174  24/05/2024  Geography           Present             P
28     S04411  05/06/2024    History            Absent             F
29     S02538  02/08/2024    History            Absent             F
30     S11397  19/01/2025    History            Absent             F
31     S03733  24/06/2024    History          Present              P
32     S03711  19/01/2025    History            Absent             F
33     S07782  19/03/2024    History          Present              P
34     S04730  28/01/2025    History            Absent             F
35     S04423  25/07/2024    History           Present             P
36     S07816  25/04/2024    History            Absent             F
37     S02002  24/05/2024       Math          Present              P
38     S11075  17/06/2024       Math            Absent             F
39     S01777  22/01/2025       Math           Present             P
40     S04868  14/10/2024       Math            Absent             F
41     S06390  02/08/2024       Math           Present             P
42     S11830  11/02/2025       Math            Absent             F
43     S08373  13/05/2024       Math            Absent             F
44     S10058  18/01/2025       Math            Absent             F
45     S09880  05/05/2024       Math           Present             P
46     S02096  01/01/2025       Math           Present             P
47     S03714  01/07/2024    Science            Absent             F
48     S09400  12/12/2024    Science            Absent             F
49     S03919  31/10/2024    Science            Absent             F
50     S00923  07/10/2024    Science            Absent             F
51     S06107  14/11/2024    Science          Present              P
52     S05335  21/11/2024    Science           Present             P

In [ ]:
from google.colab import files

df.to_csv('attendance.csv', index=False)
files.download('attendance.csv')